### ISSUE TITLE
VPN not terminated properly for Prometheus sidecar

### ISSUE THREAD

**Issue by wyb1** [gardener/vpn#55] opened 2020-04-20 07:37 UTC
**What happened**:
VPN is a sidecar to Prometheus and whenever Prometheus gets restarted, VPN does not get terminated properly causing Prometheus to hang in termination until the terminationGracePeriod is exceeded. 

**What you expected to happen**:
VPN should terminate its process allowing the Prometheus pod to gracefully shutdown.

**How to reproduce it (as minimally and precisely as possible)**:
On any control plane, kill the Prometheus pod and it will hang.

**Anything else we need to know**:

**Environment**:

**Comment by zanetworker** [comment] 2020-04-24 12:13
I quickly looked into it, VPN does correctly handle SIGTERM but in this case, it was never sent to the VPN.

**Comment by vlerenc** [comment] 2020-05-01 14:30
@wyb1 and @zanetworker and now. Haven't we seen the VPN continuing to run @wyb1 . Since P dies/gets up-scaled now and then and we need monitoring, it's painful to have a 5m, now still 1m hole in our data.

**Comment by vlerenc** [comment] 2020-05-01 15:00
I can confirm, that the VPN container blocks the termination. When I delete a P pod, all 3 other containers cease their execution, but the VPN container remains running for a minute.

**Comment by vlerenc** [comment] 2020-05-01 15:00
<img width="1639" alt="Screenshot 2020-05-01 at 16 57 59" src="https://user-images.githubusercontent.com/4974203/80815100-517e2700-8bcd-11ea-9723-bbd46c484cc3.png">

**Comment by zanetworker** [comment] 2020-06-10 11:54
Closing now since VPN is no longer used for the prometheus side-car after https://github.com/gardener/gardener/pull/2251 

Please re-open if you think its still relevant.

**Closed as completed** 2020-06-10 11:55 UTC
Labels: kind/bug

**Comment by vlerenc** [comment] 2020-06-10 12:12
Well, that's the best of all answers @zanetworker . :-)
